### ISSUE TITLE
微信小程序pc端报错麻烦支持下

### ISSUE THREAD

**Issue by cuikangyi** [tarojsx/polyfill#2]
![image](https://user-images.githubusercontent.com/5945838/82533166-53f0f280-9b75-11ea-9009-295b134ba97f.png)
注入下window.Date.now，或者能找到window.performance对象都可以解决

**Comment by cncolder** [comment]
@cuikangyi 这是哪个模块里的代码片段?
如果 pc 版小程序没有 window.Date, 那其他的会有么? setTimeout clearTimeout.

**Comment by cuikangyi** [comment]
@cncolder 
这个是Taro编译时候的vendor.js，Taro直接编译在pc端小程序运行就会报错，我截图是使用了你的polyfill之后的，可以看到上面的performance.now注入了，还有两个animation也注入了，但是缺少performance对象，也没有Date，所以我圈起来的if那段会报错
你可以试下

**Comment by cncolder** [comment]
@cuikangyi 首先你要明白什么是 polyfill, 当运行环境不支持某些特性时, 采用旧的 api 模拟新的 api.

例如 taro 运行时不支持 performance.now, 于是我们使用 "当前时间" 减去 "初始时间". Date.now() - startTime.

如果要支持上面的写法, 可能需要注入的是 window.Date window.setTimeout window.clearTimeout

上面截图里的代码是你自己写的么? 还是你用到的某个 npm 包里的源码? 如果我知道这个包名, 可以有针对的测试一下. 还有这个问题只发生在 PC 小程序上吗?

**Comment by cncolder** [comment]
明天问一下 taro 那边, 为什么 window.Date 和 window.setTimeout 只在头条/百度/京东三种小程序里保存在 window 对象下. https://github.com/NervJS/taro/blob/v3.0.0-rc.0/packages/taro-runtime/src/bom/window.ts

**Comment by cuikangyi** [comment]
@cncolder 谢谢解答
对webpack的不是很熟，通过查看包的依赖关系发现，tarojs@react依赖了react-reconciler而react-reconciler又依赖这个scheduler，我测试了下直接taro init的项目，默认模板下打包之后的vendor.js中不会出现截图中的scheduler代码，而使用redux初始化后会出现
这个是我使用redux模板在pc上运行的截图，出错的地方就是我上面说的那个Date.now，用了你这个包上面前两个错误可以解决
![image](https://user-images.githubusercontent.com/5945838/82770412-0de4a900-9e6b-11ea-865b-404cee342bed.png)

看了下taro-runtime的代码，应该问题就出在这，昨天也在微信群里问了taro的人，他们也没回复

**Comment by cncolder** [comment]
@cuikangyi Taro3 里 window 对象是伪造的, 目前 window 对象下面只有 navigator 和 document 两个字段, 有没有 window 对象可能引起一些库的行为发生变化. 如果你觉得 redux 模板有问题, 可以向 taro 提 issus.

虽然 window 对象本身也是通过 webpack.ProvidePlugin 做到全局可用的, 但使用插件定义的 window.Date 和 window 对象本身就有 Date 是不同的, 不敢保证会不会带来其他问题.

你尝试一下在 app.js 最开头的地方自己设置一下.

```js
window.Date = window.Date || Date
window.setTimeout = window.setTimeout || setTimeout
```

**Comment by cuikangyi** [comment]
@cncolder 好的，试过再app.js里面设置是不行，报错是在vendor.js里
那能不能通过注入一个performance对象，让 typeof performance == 'object' 为true呢，这样也是可以的

**Comment by cuikangyi** [comment]
谢谢您的解答
我还是先去问下taro-runtime那里为什么忽略微信小程序对window的处理吧，如果runtime那边给了，也不用注入了，我先关了，有问题的话再请教你

**Comment by cncolder** [comment]
@cuikangyi performance 不是一个简单的对象, 你在浏览器控制台里可以看一下.

Performance 是一个复杂的类实例, 如果只是简单的设置为 {}, 不知道还会有多少第三方库出问题.

**Comment by cuikangyi** [comment]
谢谢，受教了
